AllAboutPigeons/Controllers/MessageController.cs
using AllAboutPigeons.Data;
using AllAboutPigeons.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AllAboutPigeons.Controllers
{
    public class MessageController : Controller
    {
        // AppDbContext context;
        readonly IMessageRepository _repository;
        readonly UserManager<AppUser> _userManager;

        public MessageController(IMessageRepository r, UserManager<AppUser> u)
        {
            _repository = r;
            _userManager = u;
        }

        // TODO: Do something interesting with the messageId
        public IActionResult Index()
        {
            var messages = _repository.GetMessages();
            // Get the last post out of the database
            // .Where(m => m.MessageId == int.Parse(messageId))
            // .FirstOrDefault();
            // .Find(int.Parse(messageId));
            return View(messages);
        }

        [HttpPost]
        public IActionResult Index(string toname)
        {
            var messages = _repository.GetMessages()
                .Where(m => m.To.Name == toname)
                .ToList<Message>();

            return View("Index", messages);
        }

        [Authorize]
        public IActionResult ForumPost()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ForumPost(Message model)
        {
            model.Date = DateOnly.FromDateTime(DateTime.Now);
            if (_userManager != null) // Don't get a user when doing unit tests
            {
                // Get the sender
                model.From = _userManager.GetUserAsync(User).Result;
                // Check to see if the recipient user name matches a registered user
                AppUser recipient = _userManager.FindByNameAsync(model.To.Name).Result;
                if (recipient != null)
                {
                    model.To = recipient;
                }
            }

            // Temporarily add a random rating to the post
            // TODO: Add a way for users to rate messages, or remove ratings
            Random random = new Random();
            model.Rating = random.Next(0, 10);

            if (model.To.UserName != null) // check for valid recipient
            {
                // Save the message
                await _repository.StoreMessageAsync(model);
                //TODO: Do something interesting/useful with the MessageId or don't send it. It's not currently used.
                return RedirectToAction("Index", new { model.MessageId });
            }
            else
            {
                ModelState.AddModelError("", "Recipient not a registered user");
                return View(model);
            }
        }

        [Authorize]
        public IActionResult Reply(int? OriginalMessageId)
        {
            Message reply = new Message();
            reply.OriginalMessageId = OriginalMessageId;
            return View(reply);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Reply(Message reply)
        {
            reply.Date = DateOnly.FromDateTime(DateTime.Now);
            if (_userManager != null) // Don't get a user when doing unit tests
            {
                // Get the sender
                reply.From = _userManager.GetUserAsync(User).Result;
            }
            // Get the message being replied to (guarantted to be not null by design)
            Message originalMessage = await _repository.GetMessageByIdAsync(reply.OriginalMessageId.Value);
            // Get the recipient
            reply.To = originalMessage.From;
            // Save the message
            await _repository.StoreMessageAsync(reply);
            // Add the reply to the original message
            originalMessage.Replies.Add(reply);
            _repository.UpdateMessage(originalMessage);
            //TODO: Do something interesting/useful with the MessageId or don't send it. It's not currently used.
            return RedirectToAction("Index", new { reply.MessageId });
        }

        public IActionResult DeleteForumPost(int messageId)
        {
            // TODO: Do something like redirect if the delete fails
            _repository.DeleteMessage(messageId);
            return RedirectToAction("Index");
        }

        public IActionResult Info()
        {
            return View();
        }
    }
}

AllAboutPigeons/Controllers/QuizController.cs
using AllAboutPigeons.Models;
using Microsoft.AspNetCore.Mvc;

namespace AllAboutPigeons.Controllers
{
    public class QuizController : Controller
    {
        public Dictionary<int, String> Questions { get; set; }
        public Dictionary<int, String> Answers { get; set; }

        public QuizController()
        {
            // Temporary set of hard-coded questions
            // In the future we'll read these from a file.
            Questions = new Dictionary<int, String>();
            Answers = new Dictionary<int, String>();
            Questions[1] = "Are all pigeons homing pigeons? (Yes or No)";
            Answers[1] = "No";
            Questions[2] = "Are all pigeons secretly government spies? (Yes, No, Some)";
            Answers[2] = "Some";
            Questions[3] = "Where do pigeons sleep (Name an official building)";
            Answers[3] = "The Pentagon";
        }

        public IActionResult Index()
        {
            var model = LoadQuestions(new QuizQuestions());
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(string answer1, string answer2, string answer3) 
        { 
            var model = LoadQuestions(new QuizQuestions());
            model.UserAnswers[1] = answer1;
            model.UserAnswers[2] = answer2;
            model.UserAnswers[3] = answer3;
            // Check the user's answers
            var checkedModel = CheckQuizAnswers(model);
            return View(checkedModel);
        }

        public QuizQuestions LoadQuestions(QuizQuestions model)
        {
            // load questions and answers into the model
            model.Questions = Questions;
            model.Answers = Answers;
            // TODO: Should these objects be created in the model?
            model.UserAnswers = new Dictionary<int, string>();
            model.Results = new Dictionary<int, bool>();
            // create empty entries for each question
            foreach (var question in Questions)
            {
                int key = question.Key;
                model.UserAnswers[key] = "";
            }

            return model;
        }

        public QuizQuestions CheckQuizAnswers(QuizQuestions model) 
        { 
            foreach (var question in Questions) 
            {
                int key = question.Key;
                model.Results[key] = model.Answers[key] == model.UserAnswers[key];
            }
            return model;
        }
    }
}

AllAboutPigeons/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AllAboutPigeons.Models;
using Microsoft.AspNetCore.Authorization;

namespace AllAboutPigeons.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<AppUser> userMngr,
            RoleManager<IdentityRole> roleMngr)
        {
            _userManager = userMngr;
            _roleManager = roleMngr;
        }

        public async Task<IActionResult> Index()
        {
            List<AppUser> users = new List<AppUser>();
            foreach (AppUser user in _userManager.Users.ToList())
            {
                user.RoleNames = await _userManager.GetRolesAsync(user);
                users.Add(user);
            }
            UserVm model = new UserVm
            {
                Users = users,
                Roles = _roleManager.Roles
            };
            return View(model);
        }

        public IActionResult Add()
        {
            return View("../Account/Register");
        }

        [HttpPost]
        public async Task<IActionResult> Add(RegisterVm model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName = model.Username };
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View("../Account/Register", model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (!result.Succeeded) // if failed
                {
                    string errorMessage = "";
                    foreach (IdentityError error in result.Errors)
                    {
                        errorMessage += error.Description + " | ";
                    }
                    TempData["message"] = errorMessage;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddToAdmin(string id)
        {
            IdentityRole adminRole = await _roleManager.FindByNameAsync("Admin");
            if (adminRole == null)
            {
                TempData["message"] = "Admin role does not exist. "
                    + "Click 'Create Admin Role' button to create it.";
            }
            else
            {
                AppUser user = await _userManager.FindByIdAsync(id);
                await _userManager.AddToRoleAsync(user, adminRole.Name);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            var result = await _userManager.RemoveFromRoleAsync(user, "Admin");
            if (result.Succeeded) { }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdminRole()
        {
            var result = await _roleManager.CreateAsync(new IdentityRole("Admin"));
            // TODO: Do something with the result or get rid of the bogus if
            if (result.Succeeded) { }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded) { }
            return RedirectToAction("Index");
        }

    }
}

AllAboutPigeons/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - All About Pigeons</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AllAboutPigeons.styles.css" asp-append-version="true" />
</head>
<body>

<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">All About Pigeons</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Index">Quiz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Index">Messages</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="User" asp-action="Index"><span class="fas fa-cog"></span>&nbsp;Admin</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                        // Signed-in user - show Log Out button and username
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <input type="submit" value="Log Out" class="btn btn-outline-dark" />
                                    <span class="text-dark">@User.Identity.Name</span>
                                </form>
                            </li>
                        }
                        else
                        {
                            // anonymous user - show Register link and Log In button
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">
                                    <span class="fas fa-edit"></span> &nbsp; Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Login" asp-controller="Account" class="btn btn-outline-dark">
                                    Log In
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AllAboutPigeons - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>